# Generated by Django 4.1.2 on 2022-12-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='closing_day',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_day',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='business_times',
            field=models.CharField(blank=True, help_text='For example: Tuesday to Sunday, 10:00 to 22:00', max_length=150, null=True),
        ),
    ]
