# Generated by Django 4.1.2 on 2022-12-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_closing_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_times',
            field=models.CharField(blank=True, help_text='For example: Tuesday to Sunday, 10:00 to 22:00 OR Weekdays 10:00 to 21:00', max_length=150, null=True),
        ),
    ]
