# Generated by Django 4.1.2 on 2022-12-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_business_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='food_sold',
            field=models.CharField(blank=True, help_text='Enter coma separated main types of food sold by restaurant', max_length=200, null=True),
        ),
    ]
