# Generated by Django 4.1.2 on 2022-12-10 07:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_contact_number_activity_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='contact_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, help_text='Excerpt is made from the first paragraph of content', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='facebook_page_link',
            field=models.URLField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='facebook_page_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='twitter_profile_link',
            field=models.URLField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='website',
            field=models.URLField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
