# Generated by Django 4.1.2 on 2022-12-10 07:52

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('thumb_nail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, help_text='Select the number of start as per the Tourism Grading Council', verbose_name='Star rating')),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('website', models.URLField(blank=True, db_index=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook_page_name', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook_page_link', models.URLField(blank=True, db_index=True, max_length=150, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_profile_link', models.URLField(blank=True, db_index=True, max_length=150, null=True)),
                ('published', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Attractions',
            },
        ),
    ]
