# Generated by Django 4.1.2 on 2022-12-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='stars',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, help_text='Select the number of start as per the Tourism Grading Council', verbose_name='Star rating'),
        ),
    ]
